# Assignment 4 - Predictive Policing

## Nourhan El Zarif

## Read & Clean Dataset

In [1]:
import pandas as pd
import numpy as np

file = 'http://archive.ics.uci.edu/ml/machine-learning-databases/communities/communities.data'
#https://archive.ics.uci.edu/ml/datasets/Communities+and+Crime

col_names = ['state','county','community','communityname','fold','population','householdsize','racepctblack','racePctWhite','racePctAsian','racePctHisp','agePct12t21','agePct12t29','agePct16t24','agePct65up','numbUrban','pctUrban','medIncome','pctWWage','pctWFarmSelf','pctWInvInc','pctWSocSec','pctWPubAsst','pctWRetire','medFamInc','perCapInc','whitePerCap','blackPerCap','indianPerCap','AsianPerCap','OtherPerCap','HispPerCap','NumUnderPov','PctPopUnderPov','PctLess9thGrade','PctNotHSGrad','PctBSorMore','PctUnemployed','PctEmploy','PctEmplManu','PctEmplProfServ','PctOccupManu','PctOccupMgmtProf','MalePctDivorce','MalePctNevMarr','FemalePctDiv','TotalPctDiv','PersPerFam','PctFam2Par','PctKids2Par','PctYoungKids2Par','PctTeen2Par','PctWorkMomYoungKids','PctWorkMom','NumIlleg','PctIlleg','NumImmig','PctImmigRecent','PctImmigRec5','PctImmigRec8','PctImmigRec10','PctRecentImmig','PctRecImmig5','PctRecImmig8','PctRecImmig10','PctSpeakEnglOnly','PctNotSpeakEnglWell','PctLargHouseFam','PctLargHouseOccup','PersPerOccupHous','PersPerOwnOccHous','PersPerRentOccHous','PctPersOwnOccup','PctPersDenseHous','PctHousLess3BR','MedNumBR','HousVacant','PctHousOccup','PctHousOwnOcc','PctVacantBoarded','PctVacMore6Mos','MedYrHousBuilt','PctHousNoPhone','PctWOFullPlumb','OwnOccLowQuart','OwnOccMedVal','OwnOccHiQuart','RentLowQ','RentMedian','RentHighQ','MedRent','MedRentPctHousInc','MedOwnCostPctInc','MedOwnCostPctIncNoMtg','NumInShelters','NumStreet','PctForeignBorn','PctBornSameState','PctSameHouse85','PctSameCity85','PctSameState85','LemasSwornFT','LemasSwFTPerPop','LemasSwFTFieldOps','LemasSwFTFieldPerPop','LemasTotalReq','LemasTotReqPerPop','PolicReqPerOffic','PolicPerPop','RacialMatchCommPol','PctPolicWhite','PctPolicBlack','PctPolicHisp','PctPolicAsian','PctPolicMinor','OfficAssgnDrugUnits','NumKindsDrugsSeiz','PolicAveOTWorked','LandArea','PopDens','PctUsePubTrans','PolicCars','PolicOperBudg','LemasPctPolicOnPatr','LemasGangUnitDeploy','LemasPctOfficDrugUn','PolicBudgPerPop','ViolentCrimesPerPop']

The data was imported with all missing values interpreuted as NaN. These values will be dropped as a quick measure to clean the dataset.

In [2]:
data = pd.read_csv(file, header = None, names = col_names, na_values=["?"])

print(data.shape)
data.head()

(1994, 128)

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
0,8,NaN,NaN,Lakewoodcity,1,0.19,0.33,0.02,0.90,0.12,...,0.12,0.26,0.20,0.06,0.04,0.9,0.5,0.32,0.14,0.20
1,53,NaN,NaN,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,...,0.02,0.12,0.45,NaN,NaN,NaN,NaN,0.00,NaN,0.67
2,24,NaN,NaN,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,...,0.01,0.21,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.43
3,34,5.0,81440.0,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,...,0.02,0.39,0.28,NaN,NaN,NaN,NaN,0.00,NaN,0.12
4,42,95.0,6096.0,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,...,0.04,0.09,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.03

After dropping all NaN values, the number of rows decreases from 1994 instances to 123 instances.

In [3]:
#clean the data
data.dropna(inplace = True)

print(data.shape)
data.head()

(123, 128)

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
16,36,1.0,1000.0,Albanycity,1,0.15,0.31,0.40,0.63,0.14,...,0.06,0.39,0.84,0.06,0.06,0.91,0.5,0.88,0.26,0.49
23,19,193.0,93926.0,SiouxCitycity,1,0.11,0.43,0.04,0.89,0.09,...,0.16,0.12,0.07,0.04,0.01,0.81,1.0,0.56,0.09,0.63
33,51,680.0,47672.0,Lynchburgcity,1,0.09,0.43,0.51,0.58,0.04,...,0.14,0.11,0.19,0.05,0.01,0.75,0.0,0.60,0.10,0.31
68,34,23.0,58200.0,PerthAmboycity,1,0.05,0.59,0.23,0.39,0.09,...,0.01,0.73,0.28,0.00,0.02,0.64,0.0,1.00,0.23,0.50
74,9,9.0,46520.0,Meridentown,1,0.08,0.39,0.08,0.85,0.04,...,0.07,0.21,0.04,0.02,0.01,0.70,1.0,0.44,0.11,0.14

I will aslo drop community name because it is a string. We can see the number of columns decrease by 1.

In [4]:
data.drop(columns='communityname', inplace=True)
data.shape

(123, 127)

To avoid target leakage, I will seperate the goal from the other attributes.

In [5]:
#ViolentCrimesPerPop
target = data['ViolentCrimesPerPop']
target.head()

16    0.49
23    0.63
33    0.31
68    0.50
74    0.14
Name: ViolentCrimesPerPop, dtype: float64

In [6]:
data.drop(columns='ViolentCrimesPerPop', inplace=True)
data.shape

(123, 126)

In [7]:
data.head()

,state,county,community,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,...,PolicAveOTWorked,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop
16,36,1.0,1000.0,1,0.15,0.31,0.40,0.63,0.14,0.06,...,0.22,0.06,0.39,0.84,0.06,0.06,0.91,0.5,0.88,0.26
23,19,193.0,93926.0,1,0.11,0.43,0.04,0.89,0.09,0.06,...,0.29,0.16,0.12,0.07,0.04,0.01,0.81,1.0,0.56,0.09
33,51,680.0,47672.0,1,0.09,0.43,0.51,0.58,0.04,0.01,...,0.10,0.14,0.11,0.19,0.05,0.01,0.75,0.0,0.60,0.10
68,34,23.0,58200.0,1,0.05,0.59,0.23,0.39,0.09,1.00,...,0.31,0.01,0.73,0.28,0.00,0.02,0.64,0.0,1.00,0.23
74,9,9.0,46520.0,1,0.08,0.39,0.08,0.85,0.04,0.25,...,0.31,0.07,0.21,0.04,0.02,0.01,0.70,1.0,0.44,0.11

## Filter Selection - Mutual Information
Filter Selection can use mutual information or correlation.

In [8]:
from sklearn.metrics import mutual_info_score

def calc_MI(x, y, bins):
    c_xy = np.histogram2d(x, y, bins)[0]
    mi = mutual_info_score(None, None, contingency=c_xy)
    return mi

mi_df = pd.DataFrame(columns=['col_index', 'MI'])

#The MI will be calculated for every column, then appended to a dataframe
for col in data.columns:
    mi = calc_MI(target, data[col], 20)
    mi_df = mi_df.append({'col_index': col, 'MI' : mi}, ignore_index=True)
    #print("Mutual information=%.2f"%mi)

After calculating the mutual information for every column, we can see the top 10 attributes.

In [9]:
mi_df.sort_values(by='MI', ascending = False).head(12)

              col_index        MI
48          PctKids2Par  1.477514
49     PctYoungKids2Par  1.376339
54             PctIlleg  1.369786
50          PctTeen2Par  1.359973
47           PctFam2Par  1.353806
21          pctWPubAsst  1.346003
78     PctVacantBoarded  1.259727
36        PctUnemployed  1.248537
7          racePctWhite  1.221677
108  RacialMatchCommPol  1.213487
43       MalePctNevMarr  1.198643
32       PctPopUnderPov  1.193319

## Wrapper - Backward Model Selection
The wrapper method includes forward/backwards step-wise selection.

In [10]:
#using recursive feature elimination library
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression

estimator = LinearRegression()
selector = RFE(estimator, 12, step=5)
selector = selector.fit(data, target)
print(selector.support_)
print(selector.ranking_)

[False False False False False  True False False False False False  True
 False False False False  True False False False False False False  True
 False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False  True  True
 False False False False False False  True  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False  True False False False  True
 False False False False False False False False False False False False
 False False False False False False]
[24 24 24 24  4  1 22 13 18 12 13  1 10 11 17  8  1 21 21 21 22 20 15  1
 22 10  5 15  8 18 19  7 23 14 13 16  1  2  3  7 12 11  9 20 16 16 14 16
 15 10 23  7  6  8 11 20  8  3  1  1  9  9  4  4 17 11  1  1  8 17 15 16
 13 12 15  4 12  6  7  5 18 17 18  7  6 10  2  3  5  6  5 19 17 21 23  6
 22 14 13 20 19  1  3  1  9  5  4  1  9 20 14 10 19 14  2 19 23  3 11 12
 22 21  2 23 24 18]

The recursive feature elimination returned a list of booleans that represents whether an attribute is one of the selected 10 features. 

To get the names of the attributes, I itterated over the list and appended the indices where the value is true.

In [11]:
wrapper = []

for val in range(len(selector.support_)):
    if (selector.support_[val] == True):
        wrapper.append(data.columns[val])

print(wrapper)

['householdsize', 'agePct12t29', 'medIncome', 'medFamInc', 'PctUnemployed', 'PctImmigRec8', 'PctImmigRec10', 'PctLargHouseFam', 'PctLargHouseOccup', 'LemasSwFTPerPop', 'LemasSwFTFieldPerPop', 'PolicPerPop']

## Embedded -  Lasso Regression

In [12]:
from sklearn import linear_model

clf = linear_model.Lasso(alpha = 0.005)
clf.fit(data, target)

print(clf.coef_)

print(clf.intercept_)

[-2.54854150e-03  1.50652466e-06 -8.56352230e-07 -4.82696911e-03
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.40040762e-01
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  3.04910658e-01 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -1.09851762e-01
 -0.00000000e+00 -0.00000000e+00 -1.62355842e-02  0.00000000e+00
  0.00000000e+00  0.00000000e+00  4.51592229e-02  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  1.25615788e-01 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  4.01968103e-03  0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  1.04228130e-02  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00]
0.5851531720141881

Lasso regression shows us which features were shrunk down to 0. The remaining ones will be used for feature selectoin.

In [13]:
lasso = []

for val in range(len(clf.coef_)):
    if (clf.coef_[val] != 0):
        lasso.append(data.columns[val])
        
print(lasso)

['state', 'county', 'community', 'fold', 'racePctWhite', 'pctWPubAsst', 'PctFam2Par', 'PctTeen2Par', 'PctIlleg', 'PctVacantBoarded', 'NumInShelters', 'PopDens']

# Results

Three feature selection methods were implemented. 

Mutual Information was used for the filter selection method. The following features were selected:
1. PctKids2Par
2. PctYoungKids2Par
3. PctIlleg
4. PctTeen2Par
5. PctFam2Par
6. pctWPubAsst
7. PctVacantBoarded
8. PctUnemployed 
9. racePctWhite 
10. RacialMatchCommPol 
11. MalePctNevMarr
12. PctPopUnderPov 


For the wrapper method, I used Backwards Model Selection. The following features were selected:
1. householdsize
2. agePct12t29
3. medFamInc
4. PctImmigRec8
5. PctImmigRec10
6. PctLargHouseFam
7. PctLargHouseOccup
8. LemasSwFTPerPop
9. LemasSwFTFieldPerPop
10. PolicPerPop
11. medIncome
12. PctUnemployed


For the embedded method, I used Lasso Regression. The following features were selected:
1. state
2. county
3. community
4. fold
5. racePctWhite
6. pctWPubAsst
7. PctFam2Par
8. PctTeen2Par
9. PctIlleg
10. PctVacantBoarded
11. NumInShelters
12. PopDens

The wrapper method has the most unique attribute selection. The wrapper method only had one common slected attribute with the filter method. The wrapper method had no common selected attributes with the embedded method. 


The embedded and filter methods, on the other hand, had some common features selected. It includes the following features:
1. racePctWhite
2. pctWPubAsst
3. PctFam2Par
4. PctTeen2Par
5. PctIlleg
6. PctVacantBoarded